name: rebase

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
  
env:
  UPSTREAM_GIT: https://github.com/Manjaro-Sway/sworkstyle.git

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v2.3.4
      with:
        token: ${{ secrets.PUSH_AND_TRIGGER }}
    - 
      name: add ssh pk
      if: ${{ contains(env.UPSTREAM_GIT, 'ssh') }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_BASE64 }}" | base64 -d >~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
        [ -f .github/additional_known_hosts ] && cat .github/additional_known_hosts >> ~/.ssh/known_hosts
    - 
      name: check if behind upstream
      run: |
        git remote add upstream ${UPSTREAM_GIT}
        git fetch upstream
        git merge-base --is-ancestor $(git branch --show-current) upstream/$(git branch --show-current) && exit 1 || exit 0
    - 
      name: rebase
      if: ${{ failure() }}
      run: |
        git rebase upstream/$(git branch --show-current)
        git push --force-with-lease