name: resubmit the release

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 1-23/2 * * *'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  resubmit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [stable, testing, unstable]
    steps:
      - id: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - id: versions
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          versions="$(gh release list --limit 3 | grep \"${{ matrix.branch }}\" | head -1 | awk '{print $1;}')"
          echo "versions=${versions}" >> $GITHUB_OUTPUT
      - name: dispatch
        uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588 # v2
        with:
          token: ${{ secrets.DISPATCH }}
          repository: manjaro-sway/packages
          event-type: package_update
          client-payload: '{ "repository": "${{ github.repository }}", "version": "${{ steps.version.outputs.versions }}" }'
